### ISSUE TITLE
can you provider your codes about your module FLGC based on tensorflow?

### ISSUE THREAD

**Issue by longmalongma** [Daniil-Osokin/fully-learnable-group-convolution.pytorch#9]
How to implement the module FLGC based on tensorflow? Because my codes is based on tensorflow, I want to introduce your flgc and cite your paper. can you provider your codes about your module FLGC based on tensorflow? looking forward to your reply.

**Comment by Daniil-Osokin** [comment]
Hi! This is just a possible implementation, I am not the one of paper authors. [Implementation notes](https://github.com/Daniil-Osokin/fully-learnable-group-convolution.pytorch#implementation-notes) describe the thoughts about limitation of this (and follow up) approach for practical usage, because there is no such built-in layer, which supports grouping with custom (not uniform) input channels/filters split. This needs to be taken into account. I do not have plans to port this code in TensorFlow.

**Comment by Daniil-Osokin** [comment]
Hope, it is clear now.
